version: '3.8'

services:

  sql_agent:
    build: 
      context: agents/sql_agent
      dockerfile: Dockerfile
    container_name: sql_agent
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_QUEUE_NAME=${RABBITMQ_QUEUE_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - agent_network

  gpto_agent:
    build: 
      context: agents/gpto_agent
      dockerfile: Dockerfile
    container_name: gpto_agent
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - RABBITMQ_QUEUE_NAME=${RABBITMQ_QUEUE_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "5000:5000" 
    networks:
      - agent_network

networks:
  agent_network:
    driver: bridge
